title: Antonio Al Makdissi
description: Data Scientist
site_title: '@mcdc - AntonioMakdissi'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://www.nagekar.com
email: antoniomakdissi1@gmail.com
keybase_username: abhn
twitter_username: mcdc_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 