title: Antonio Al Makdissi
description: Data Scientist
site_title: '@mcdc - AntonioMakdissi'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: AntonioMakdissi
blog_url: https://www.nagekar.com
email: antoniomakdissi1@gmail.com
keybase_username: mcdc
twitter_username: mcdc_
reddit_username: mcdc

# absolute or relative
profile_picture: assets/images/pp.png

# Google Analytics ID
google_analytics: 