title: Antonio Al Makdissi
description: Data Scientist
site_title: '@AntonioMakdissi'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: AntonioMakdissi
blog_url: https://github.com/AntonioMakdissi/my-business-card/releases/download/v1.0.3.4/card.pdf
email: antoniomakdissi1@gmail.com
keybase_username: mcdc
twitter_username: mcdc_
reddit_username: mcdc1
linkedIn_url: https://www.linkedin.com/in/antonio-al-makdissi/

# absolute or relative
profile_picture: assets/images/profile_pic.jpeg
# Google Analytics ID
google_analytics: 